workspace:
  base: /go
  path: baa-cicd
pipeline:
  build:
    image: golang:latest
    commands:
      - go build -o go
  scp:
    image: appleboy/drone-scp
    host: 192.168.110.12
    username: root
    password: DtDream01
    rm: true
    target:
     - /tmp/drone
    source:
     - go
  dingtalk:
    image: lddsb/drone-dingtalk-message
    settings:
      token: d93f58ca06051be5c0b6a6211ebd1d8ef10fa6fa5e03b46beba102ae0cee9ac4
      sha_link: true
      type: markdown
    when:
      status: [failure, success]
