workspace:
  base: /go
  path: baa-cicd
pipeline:
  build:
    image: golang:latest
    commands:
      - go build -o go
  scp:
    image: appleboy/drone-scp
    host: 192.168.110.12
    username: root
    password: DtDream01
    rm: true
    target:
     - /tmp/drone
    source:
     - go
  dingtalk:
    image: xtony77/drone-dingtalk
    webhook: https://oapi.dingtalk.com/robot/send?access_token=XXXXXXXXXXXXXXXXXXX
    when:
      status: [failure, success]
  dingtalk_secret:
    image: xtony77/drone-dingtalk
    secrets:
      - source: dingding
        target: plugin_webhook
    when:
      status: [ failure, success ]
  notification:
    image: guoxudongdocker/drone-dingtalk
    token: XXXXXXXXXXXXXX10fa6fa5e03b46beba102ae0cee9ac4
    type: markdown
    message_color: true
    message_pic: true
    sha_link: true
  #notification_secret:网上教程，测试不可用XXX
  #  image: guoxudongdocker/drone-dingtalk
  #  settings:
  #    token:
  #      from_secret: dingtalk
  #    type: markdown
  #    message_color: true
  #    message_pic: true
  #    sha_link: true
