workspace:
  base: /go
  path: baa-cicd
pipeline:
  build:
    image: golang:latest
    commands:
      - go build -o go
  scp:
    image: appleboy/drone-scp
    host: 192.168.110.12
    username: root
    password: DtDream01
    rm: true
    target:
     - /tmp/drone
    source:
     - go
  dingtalk:
    image: guoxudongdocker/drone-dingtalk
    setting:
      token:
        from_secret: dingding
      type: markdown
      message_color: true
      message_pic: true
      sha_link: true
    when:
      status: [failure, success]
